POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVza2FyIiwiaWQiOiI1ZjA4YTA3NjQ3MzZhNjRlNmM1MWI0NDEiLCJpYXQiOjE1OTQ0MDY2NDJ9.tEOVZ9Yx7sVkrScccg-9dtXzxM2SNjxR5OHM9HYFW0g

{
  "title": "FifthBlog",
  "author": "Some Guy",
  "url": "www.fifthblog.com",
  "likes": 68
}